	gcc unittest1.c dominion.c rngs.c -lm -o unittest1
	gcc unittest2.c dominion.c rngs.c -lm -o unittest2
	gcc unittest3.c dominion.c rngs.c -lm -o unittest3
	gcc unittest4.c dominion.c rngs.c -lm -o unittest4
	gcc cardtest1.c dominion.c rngs.c -lm -o cardtest1
	gcc cardtest2.c dominion.c rngs.c -lm -o cardtest2
	gcc cardtest3.c dominion.c rngs.c -lm -o cardtest3